### ISSUE TITLE
Cordova offline support?

### ISSUE THREAD

**Issue by ksendra** [TAPevents/tap-i18n#93] opened 2015-07-17 07:42 UTC
Hello,

do you have an estimate on when will this plugin support Cordova apps that operate offline? Not having a robust i18n support for offline apps is the only thing stopping me from doing a project in meteor...

Thanks

**Comment by theosp** [comment] 2015-07-17 08:16
There will be a new feature for v1.6 that might help with that as a side effect, but can't be sure as it is built to serve other purpose (langs preload).

If you can wait I believe that in the following months it will be developed.

If you can't wait, and you have budget to put into this feature development you are welcome to contact me by email daniel@meteorspark.com .

Thanks,
-Daniel

**Comment by derwaldgeist** [comment] 2015-09-04 13:01
Bump.

I'd also like to see offline Cordova support for tap-i18n. And no, unfortunately I don't have a budget to finance this :-) So if there are not plans to develop this in the future, I will have to look for another solution as well.

Hence, @theosp: Are there any updates on the 1.6 feature you mentioned?

**Comment by theosp** [comment] 2015-09-04 15:58
Hi,

rc for v1.6 is ready on the v1.6-rc1 branch but the support added there to
the project-tap.i18n preloaded_lang option won't help with offline support.

Due to the fact that during the build process files are built in a way that
I can't guarantee that project-tap.i18n will load before the i18n.json
files, and even worse, I can't even know for sure whether or not it will
exist as it is optional. It was too tricky to decide on the build phase
which languages files should be compiled into the build (available for
offline) and which not. As the purpose for the preloaded_lang option was
actually to do something similar to what meteorhacks:fast-render is doing
and not to support offline it was eventually implemented in a simpler way
that gave up offline support.

-Daniel

**Comment by derwaldgeist** [comment] 2015-09-04 16:04
Thanks for coming back with these insights.

I think, for Cordova it would be best if all language files are added to the build. This would also ensure that every build update pushed to the mobile client (via hot code reload) also pushes the language files there. Having the files on the client for latency compensation is more important than saving bandwidth, IMHO. Of course, it would be great if they were not all loaded into the client's memory at the same time, but loaded on demand instead (via the http://meteor:local protocol inside the Cordova app).

**Comment by theosp** [comment] 2015-09-04 18:33
Loading all the lang files to the build for the Cordova arch is tricky too...

tap:i18n was designed to be in use by both packages and the app itself. From the app build process I don't have access to the already-built i18n files of the packages the app is using - I don't even know that they exist in the build plugin context. Which means that I can't come up with a single unified asset to be built for Cordova. Therefore, building and loading all the languages asset in Cordova will have to be more sophisticated to work.

By the way, adding languages files to the build for Cordova will be a breaking change that will require a new major release.

-Daniel

**Comment by hitchcott** [comment] 2015-09-19 17:53
I've tried a few approaches, but as Daniel says the behaviour order of the `registerBuildPlugin` API can be difficult to work with. Maybe it'll be easier to achieve with the new v1.2 API, but would require a substantial rebuild either way.

Couldn't find a perfect workaround. But hopefully this is better than nothing: https://github.com/TAPevents/i18n-bundler

**Comment by derwaldgeist** [comment] 2015-09-19 23:20
Thanks for this package, will give it a try!

**Comment by theosp** [comment] 2015-09-20 04:54
Great job @hitchcott .

Added a note about this package to the README, with that, I think we can finally close this issue.

-Daniel

**Comment by theosp** [comment] 2015-10-06 08:42
Reopening, high-likely that it can be implemented with v1.2 new build plugins API as part of tap:i18n core.

**Comment by derwaldgeist** [comment] 2015-10-06 10:07
Sounds good!

**Comment by hitchcott** [comment] 2015-10-06 10:39
:fireworks:

**Comment by obiwarn** [comment] 2015-11-01 18:09
+1
We even deployed our app already to find i18n not working when offline.

**Comment by derwaldgeist** [comment] 2015-11-04 10:44
As I am getting closer to a public launch of my app, any progress on this would be highly appreciated.

**Comment by obiwarn** [comment] 2015-11-04 11:25
The 
https://github.com/TAPevents/i18n-bundler
package works well for our app. 

It is rather simple to integrate.

**Comment by derwaldgeist** [comment] 2015-11-04 18:20
Great, forgot about this new package. Thanks for reminding.

**Closed** 2023-12-02 02:50 UTC
Labels: enhancement
